//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> class_enrollment_date { get; set; }
        public Nullable<System.DateTime> class_drop_date { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> attendence_outcome { get; set; }
    
        public virtual attendence_outcome attendence_outcome1 { get; set; }
        public virtual Class Class { get; set; }
        public virtual drop_Attendence_Reason drop_Attendence_Reason { get; set; }
        public virtual Student Student { get; set; }
    }
}
