//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Schedule
    {
        public int Class_ScheduleID { get; set; }
        public Nullable<int> Class_LectureID { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
        public Nullable<System.TimeSpan> End_time { get; set; }
    
        public virtual Class_Lecture Class_Lecture { get; set; }
    }
}
