//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ClassManagementEntities : DbContext
    {
        public DB_ClassManagementEntities()
            : base("name=DB_ClassManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Attendence_outcome> Attendence_outcome { get; set; }
        public virtual DbSet<Class_Lecture> Class_Lecture { get; set; }
        public virtual DbSet<Class_Schedule> Class_Schedule { get; set; }
        public virtual DbSet<class_type> class_type { get; set; }
        public virtual DbSet<Contact_Person> Contact_Person { get; set; }
        public virtual DbSet<Contact_Person_Student> Contact_Person_Student { get; set; }
        public virtual DbSet<drop_Attendence_Reason> drop_Attendence_Reason { get; set; }
        public virtual DbSet<FeeStructure> FeeStructures { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
