//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeStructure
    {
        public int ID { get; set; }
        public Nullable<int> Class_typeID { get; set; }
        public string FeeDescription { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> Total_Amount { get; set; }
    
        public virtual class_type class_type { get; set; }
    }
}
