//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string TypeOfPayment { get; set; }
        public Nullable<int> NumberOfPayments { get; set; }
        public Nullable<long> EMI_amount { get; set; }
        public Nullable<long> AmountPaid { get; set; }
        public Nullable<long> TotalAmount { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
