//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Person_Student
    {
        public int Contact_Person_StudentID { get; set; }
        public Nullable<int> Contact_PersonID { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual Contact_Person Contact_Person { get; set; }
        public virtual Student Student { get; set; }
    }
}
